### PR TITLE
Working graphics service with tests

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by modeswitch** [comment]
We had some CSS to hide the canvas from the test output page. Add that back in and R=ack.

**Comment by secretrobotron** [comment]
Is there a reason it shouldn't be seen on the graphics test page? Is it shy?

**Comment by modeswitch** [comment]
Is the output really necessary? If it's not, I'd rather hide it and keep the tests pass/fail only. If we need to make sure the render is actually correct, we can write different tests.

**Comment by secretrobotron** [comment]
Good enough for me.

**Pull request merged**
