### PR TITLE
Fix for keyboard input on my system

### PR DESCRIPTION
**Pull request by johnoliverdriscoll**
On Chromium 18.0.1025.142 (Developer Build 129054 Linux) Ubuntu 11.10:
window is not firing keydown or keyup callbacks, however, window.document is.
This patch changes the default owner of the input component from window to window.document.
Tested in Ubuntu on Chromium 18.0.1025.142 and Firefox 11.0

### CODE REVIEW

**Comment by dmose** [comment]
Curiouser and curiouser.  After adding a console.log() to playerKeyHandler in collision-cubes.js, I see it getting invoked when I press keys in both Firefox 11 and Chrome 18 on OS X, which would seem to be different than the behavior you're seeing.  Or am I misunderstanding what you mean by it's input handler never being invoked?

**Comment by johnoliverdriscoll** [comment]
Yup, that's my issue exactly.  When I insert a console.log on line 95 (outside of the condition block), I get nothing.  Unless the above commit is applied.

**Comment by dmose** [comment]
Intriguing; that's where I put it too, and I'm seeing it logged on OS X Chrome 18.0.1025.163.  Perhaps someone has filed a bug on Webkit for Linux?

**Comment by johnoliverdriscoll** [comment]
I'm looking for a bug that fits this scenario, but, in the meantime, I've uncovered another piece to the puzzle:

In input/service.js, if you change the useCapture argument value from false to true on lines 253 and 256, then playerKeyHandler IS invoked.

**Comment by johnoliverdriscoll** [comment]
I can say for sure it's not gladius' code.  No issue found after disabling my chrome plugins.

**Comment by dmose** [comment]
Very intriguing; thanks for your work tracking down the root cause -- this'll be helpful knowledge if other folks run into something similar!

**Pull request closed without merging**
